### PR TITLE
add typescript type definitions

### PR DESCRIPTION
**Pull request by is343**

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
Hi @is343 ,
Thank you for this on-going contribution. :)
Please add me as a reviewer once the changes are done, with some instructions on how to test it.

**Comment by is343** [comment]
I used one of the samples from the nodejs-mobile-samples repo and added typescript as a dev dependency and made an `App.tsx` file from the `App.js` [here](https://github.com/is343/UseMultipleChannelsTypescriptTest).

You can just `npm install` to get typescript and my branch's nodejs-mobile-react-native ready, then just check out `App.tsx` to see the typings.

**Comment by is343** [comment]
@jaimecbernardo I don't think I have the permissions necessary to add reviewers, but I am ready for you to check this PR out. 

Let me know if you need me to change anything!

**Comment by jaimecbernardo** [comment]
Hi @is343,
Thank you for the contribution.
I've added myself as a reviewer and will give some feedback once I've been able to give it a test, but it looks good so far.

**Review by jaimecbernardo — APPROVED** [review]
It's working as expected. Thank you for the contribution!

**Pull request merged**
